---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: database-source
  namespace: source
spec:
  sourcePVC: mysql-pv-claim
  trigger:
    schedule: "*/3 * * * *"
  rsync:
    sshKeys: mysshkeys
    address: my.host.com
    copyMethod: Snapshot
