---

- name: Check for required variables
  fail: msg="Variable {{ item }} must be defined to use this role"
  when: vars[var_check] is undefined
  with_items:
    - minio_namespace
    - namespace
    - restic_secret_name
  loop_control:
    loop_var: var_check

- include_role:
    name: get_minio_credentials

- name: Create restic secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ restic_secret_name }}"
        namespace: "{{ namespace }}"
      type: Opaque
      stringData:
        RESTIC_REPOSITORY: s3:http://minio.{{ minio_namespace }}.svc.cluster.local:9000/restic-manual-trigger
        RESTIC_PASSWORD: ThisIsTheResticPassword
        AWS_ACCESS_KEY_ID: "{{ minio_access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ minio_secret_key }}"
