---
apiVersion: kuttl.dev/v1beta1
kind: TestStep
commands:
  - timeout: 300  # To wait for keys
    script: |
      set -e -o pipefail

      CONFIGDIR="$(mktemp -d)"
      KV="../../../bin/kubectl-volsync"

      "$KV" --config-dir "${CONFIGDIR}" replication -r replication create
      "$KV" --config-dir "${CONFIGDIR}" replication -r replication set-source --pvcname "${NAMESPACE}/data-source" --copymethod Snapshot
      "$KV" --config-dir "${CONFIGDIR}" replication -r replication set-destination --destination "${NAMESPACE}/data-dest" --copymethod Snapshot
      "$KV" --config-dir "${CONFIGDIR}" replication -r replication schedule --cronspec '*/5 * * * *'
