---
apiVersion: kuttl.dev/v1beta1
kind: TestAssert
timeout: 600  # Allow time for pvc->snap->pvc (on source)
collectors:
  - type: command
    command: kubectl -n "$NAMESPACE" describe all,pvc,volumesnapshot,replicationsource,replicationdestination

---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: data-dest
status:
  latestImage:
    apiGroup: snapshot.storage.k8s.io
    kind: VolumeSnapshot
