apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "volsync.backube/v1alpha1",
          "kind": "ReplicationDestination",
          "metadata": {
            "name": "replicationdestination-sample"
          },
          "spec": {
            "rsync": {
              "accessModes": [
                "ReadWriteOnce"
              ],
              "capacity": "10Gi",
              "copyMethod": "Snapshot",
              "serviceType": "ClusterIP"
            }
          }
        },
        {
          "apiVersion": "volsync.backube/v1alpha1",
          "kind": "ReplicationSource",
          "metadata": {
            "name": "replicationsource-sample"
          },
          "spec": {
            "rsync": {
              "address": "my.host.com",
              "copyMethod": "Clone",
              "sshKeys": "secretRef"
            },
            "sourcePVC": "pvcname",
            "trigger": {
              "schedule": "0 * * * *"
            }
          }
        }
      ]
    capabilities: Basic Install
    operatorframework.io/suggested-namespace: volsync-system
    operators.operatorframework.io/builder: operator-sdk-v1.14.0+git
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: volsync.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: ReplicationDestination defines the destination for a replicated
        volume
      displayName: Replication Destination
      kind: ReplicationDestination
      name: replicationdestinations.volsync.backube
      version: v1alpha1
    - description: ReplicationSource defines the source for a replicated volume
      displayName: Replication Source
      kind: ReplicationSource
      name: replicationsources.volsync.backube
      version: v1alpha1
  description: Asynchronous volume replication for Kubernetes CSI storage
  displayName: VolSync
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - batch
          resources:
          - jobs
          verbs:
          - create
          - delete
          - deletecollection
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - persistentvolumeclaims
          verbs:
          - create
          - delete
          - deletecollection
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - serviceaccounts
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - services
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - rolebindings
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - roles
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - security.openshift.io
          resourceNames:
          - privileged
          - volsync-mover
          resources:
          - securitycontextconstraints
          verbs:
          - use
        - apiGroups:
          - snapshot.storage.k8s.io
          resources:
          - volumesnapshots
          verbs:
          - create
          - delete
          - deletecollection
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - volsync.backube
          resources:
          - replicationdestinations
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - volsync.backube
          resources:
          - replicationdestinations/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - volsync.backube
          resources:
          - replicationdestinations/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - volsync.backube
          resources:
          - replicationsources
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - volsync.backube
          resources:
          - replicationsources/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - volsync.backube
          resources:
          - replicationsources/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: volsync-controller-manager
      deployments:
      - name: volsync-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=10
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources: {}
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                - --scc-name=privileged
                command:
                - /manager
                image: quay.io/backube/volsync:latest
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 200m
                    memory: 300Mi
                  requests:
                    cpu: 100m
                    memory: 20Mi
                securityContext:
                  allowPrivilegeEscalation: false
              securityContext:
                runAsNonRoot: true
              serviceAccountName: volsync-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: volsync-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - backup
  - csi
  - data
  - disaster recovery
  - replication
  - storage
  links:
  - name: Volsync
    url: https://volsync.domain
  maintainers:
  - email: jstrunk@redhat.com
    name: John Strunk
  - email: tflower@redhat.com
    name: Tesshu Flower
  maturity: alpha
  provider:
    name: Red Hat
  version: 0.0.1
