{{- if or (.Capabilities.APIVersions.Has "security.openshift.io/v1/SecurityContextConstraints") (.Values.openshift.forceSCC) }}
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: {{ include "volsync.fullname" . }}-mover
  labels:
    {{- include "volsync.labels" . | nindent 4 }}
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: false
allowPrivilegedContainer: false
allowedCapabilities:
  - AUDIT_WRITE   # for sshd
  - CHOWN         # allow files to have their uid restored
  - DAC_OVERRIDE  # allow all files in PVs to be read/written
  - FOWNER        # allow setting all file permissions & times
  - SYS_CHROOT    # for sshd
fsGroup:
  type: RunAsAny
readOnlyRootFilesystem: false
requiredDropCapabilities: [ALL]
runAsUser:
  type: RunAsAny  # allow mover to run as root
seLinuxContext:
  type: MustRunAs
seccompProfiles:
  - runtime/default
supplementalGroups:
  type: RunAsAny
volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - persistentVolumeClaim
  - projected
  - secret
{{- end }}
