---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: source
spec:
  sourcePVC: data-source
  trigger:
    manual: once
  rclone:
    rcloneConfigSection: "rclone-data-mover"
    rcloneDestPath: "test-e2e-simple-rclone"
    rcloneConfig: "rclone-secret"
    copyMethod: Snapshot
