---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: destination
spec:
  trigger:
    manual: once
  rclone:
    rcloneConfigSection: "rclone-data-mover"
    rcloneDestPath: "volsync-test-bucket"
    rcloneConfig: "rclone-secret"
    copyMethod: Snapshot
    accessModes: [ReadWriteOnce]
    capacity: 1Gi
