---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: source
spec:
  sourcePVC: data-source
  trigger:
    manual: firstsync
  rclone:
    rcloneConfigSection: "rclone-data-mover"
    rcloneDestPath: "volsync-test-bucket2"
    rcloneConfig: "rclone-secret"
    copyMethod: Snapshot
