---
apiVersion: kuttl.dev/v1beta1
kind: TestAssert
collectors:
  - type: command
    command: kubectl -n "$NAMESPACE" describe all,pvc,volumesnapshot,replicationsource,replicationdestination

---
kind: ReplicationDestination
apiVersion: volsync.backube/v1alpha1
metadata:
  name: destination
status:
  lastManualSync: firstsync
  latestImage:
    apiGroup: snapshot.storage.k8s.io
    kind: VolumeSnapshot
