---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: destination
spec:
  trigger:
    manual: firstsync
  rclone:
    rcloneConfigSection: "rclone-data-mover"
    rcloneDestPath: "test-e2e-multi-sync-snapshot-rclone"
    rcloneConfig: "rclone-secret"
    copyMethod: Snapshot
    accessModes: [ReadWriteOnce]
    capacity: 1Gi
