---
apiVersion: kuttl.dev/v1beta1
kind: TestStep
commands:
  - script: |
      set -e -o pipefail

      while [[ $(kubectl -n "$NAMESPACE" get ReplicationDestination/test -otemplate="{{.status.rsync.sshKeys}}") == "<no value>" ]]; do
          sleep 1
      done
