---
# Dump VolSync controller logs

# Try in volsync-system (Helm deployment)
- name: Collect volsync logs
  kubernetes.core.k8s_log:
    api_version: v1
    kind: Deployment
    namespace: volsync-system
    name: volsync
    container: manager
  register: volsync_logs
  failed_when: false

- name: "Print volsync logs"
  ansible.builtin.debug:
    var: volsync_logs.log_lines | map('regex_replace', '\t', '    ')

# Try in openshift-operators (OLM)
- name: Collect volsync logs
  kubernetes.core.k8s_log:
    api_version: v1
    kind: Deployment
    namespace: openshift-operators
    name: volsync-controller-manager
    container: manager
  register: volsync_logs
  failed_when: false

- name: "Print volsync logs"
  ansible.builtin.debug:
    var: volsync_logs.log_lines | map('regex_replace', '\t', '    ')
