---

# Print info from any test-* Namespaces
- name: Get a list of Namespaces in the cluster
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Namespace
  register: all_namespaces

- name: Dump contents of test namespaces
  include_tasks: dump_namespace_contents.yml
  vars:
    namespace: "{{ item }}"
  with_items: "{{ all_namespaces.resources | selectattr('metadata.name', 'match', '^test-') | map(attribute='metadata.name') }}"

- name: Dump contents of volsync namespaces
  include_tasks: dump_namespace_contents.yml
  vars:
    namespace: "{{ item }}"
  with_items:
    - volsync-system
    - openshift-operators
