---
apiVersion: kuttl.dev/v1beta1
kind: TestAssert
timeout: 600  # Allow time for pvc->snap->pvc

---
kind: ReplicationSource
apiVersion: volsync.backube/v1alpha1
metadata:
  name: source
status:
  lastManualSync: once
