---
apiVersion: kuttl.dev/v1beta1
kind: TestAssert
collectors:
  - type: command
    command: kubectl -n "$NAMESPACE" describe all,pvc,volumesnapshot,replicationsource,replicationdestination

---
apiVersion: v1
kind: Pod
metadata:
  name: verify
status:
  phase: Failed
