---
apiVersion: v1
kind: Pod
metadata:
  name: verify
spec:
  containers:
    - name: busybox
      image: busybox
      imagePullPolicy: IfNotPresent
      command: ["/bin/sh", "-c"]
      args: ["rm -rf /mnt/lost+found; rm -rf /mnt2/lost+found; diff -rs /mnt /mnt2"]
      volumeMounts:
        - name: data-src
          mountPath: "/mnt"
        - name: data-dest
          mountPath: "/mnt2"
  volumes:
    - name: data-dest
      persistentVolumeClaim:
        claimName: data-dest
    - name: data-src
      persistentVolumeClaim:
        claimName: data-source
  restartPolicy: Never
