---
apiVersion: kuttl.dev/v1beta1
kind: TestStep
delete:
  - apiVersion: batch/v1
    kind: Job
    name: verify
  - apiVersion: volsync.backube/v1alpha1
    kind: ReplicationDestination
    name: restore
