---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: destination
spec:
  trigger:
    manual: firstsync
  rsync:
    copyMethod: Snapshot
    capacity: 1Gi
    accessModes:
      - ReadWriteOnce
