---
apiVersion: kuttl.dev/v1beta1
kind: TestStep
commands:
  - script: |
      set -e -o pipefail

      KEYNAME=$(kubectl -n "$NAMESPACE" get ReplicationDestination/destination -otemplate="{{.status.rsync.sshKeys}}")
      ADDRESS=$(kubectl -n "$NAMESPACE" get ReplicationDestination/destination -otemplate="{{.status.rsync.address}}")

      kubectl -n "$NAMESPACE" apply -f - <<EOF
      ---
      apiVersion: volsync.backube/v1alpha1
      kind: ReplicationSource
      metadata:
        name: source
      spec:
        sourcePVC: data-source
        trigger:
          manual: firstsync
        rsync:
          sshKeys: $KEYNAME
          address: $ADDRESS
          copyMethod: Snapshot
      EOF
