---
apiVersion: kuttl.dev/v1beta1
kind: TestAssert
timeout: 600  # Allow time for pvc->snap->pvc
collectors:
  - type: command
    command: kubectl -n "$NAMESPACE" describe all,pvc,volumesnapshot,replicationsource,replicationdestination

---
kind: ReplicationSource
apiVersion: volsync.backube/v1alpha1
metadata:
  name: source
status:
  lastManualSync: secondsync
---
kind: ReplicationDestination
apiVersion: volsync.backube/v1alpha1
metadata:
  name: destination
status:
  lastManualSync: secondsync
  latestImage:
    apiGroup: snapshot.storage.k8s.io
    kind: VolumeSnapshot
