---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: source
spec:
  trigger:
    manual: secondsync
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: destination
spec:
  trigger:
    manual: secondsync
