---
apiVersion: kuttl.dev/v1beta1
kind: TestStep
commands:
  - script: |
      set -e -o pipefail

      SNAPNAME1=$(cat ./25-snapshot.txt)
      SNAPNAME2=$(cat ./55-snapshot.txt)

      echo "Snapshot1: $SNAPNAME1 Snapshot2: $SNAPNAME2"

      if [ "$SNAPNAME1" == "$SNAPNAME2" ]; then
        echo "ERROR snapshot from first sync ($SNAPNAME1) matches snapshot from second sync $(SNAPNAME2)"
        exit 1
      fi

      ALLSNAPSHOTS=$(kubectl -n "$NAMESPACE" get VolumeSnapshots -o custom-columns=NAME:metadata.name --no-headers)
      echo "Current volumesnapshots: $ALLSNAPSHOTS"

      # check that the old snapshot SNAPNAME1 has been removed
      if `echo "$ALLSNAPSHOTS" | grep $SNAPNAME1 >/dev/null 2>&1`; then
        echo "ERROR $SNAPNAME1 was not cleaned up"
        exit 1
      else
        echo "Old snapshot $SNAPNAME1 no longer found (successfully cleaned up)."
      fi

      # Make sure latest snapshot SNAPNAME2 is still there
      if `echo "$ALLSNAPSHOTS" | grep $SNAPNAME2 >/dev/null 2>&1`; then
        echo "Latest snapshot $SNAPNAME2 found."
      else
        echo "ERROR $SNAPNAME2 no longer exists"
        exit 1
      fi
