---
apiVersion: kuttl.dev/v1beta1
kind: TestStep
timeout: 600
commands:
  - script: |
      set -e -o pipefail

      # import the necessary utils for working w/ Syncthing
      source ./utils.sh

      # get number of syncthings in cluster
      syncthing_count=$(kubectl get replicationsource -n "${NAMESPACE}" -o jsonpath='{.items}' | jq -r 'length')
      echo "number of syncthings: ${syncthing_count}"

      i=1
      while [[ "${i}" -le "${syncthing_count}" ]]; do
        echo "waiting for syncthing-${i} to be ready..."
        replication_source="syncthing-${i}"
        wait_for_syncthing_ready "${replication_source}"
        i=$((i+1))
      done

      # loop from 1 to syncthing_count
      i=1
      while [[ "${i}" -lt "${syncthing_count}" ]]; do
        j=$((i+1))
        while [[ "${j}" -le "${syncthing_count}" ]]; do
          echo "connecting syncthing-${i} to syncthing-${j}"
          connect_syncthing "syncthing-${i}" "syncthing-${j}"
          j=$((j+1))
        done
        i=$((i+1))
      done

      echo "syncthing instances are now connected"
