---
apiVersion: kuttl.dev/v1beta1
kind: TestStep
commands:
  - timeout: 600
    script: |
      # for this test, we need to perform two checks:
      # 	1. All of the replication_sources have each other's Syncthing config in their peer list
      #   2. Each of the Syncthing IDs in .spec.syncthing.peers appears in .status.syncthing.peers and is connected

      # import the necessary utils for working w/ Syncthing
      source ./utils.sh

      echo "=== Verifying all ReplicationSources have each other in their peer list ==="
      echo "Try to verify rs are connected"
      rs_are_connected=$(verify_rs_are_connected)
      while [[ "${rs_are_connected}" -ne 0 ]]; do
        echo "Wait for all ReplicationSources to have each other in their peer list"
        sleep 5
        rs_are_connected=$(verify_rs_are_connected)
      done

      echo "=== Verifying all ReplicationSources are connected to their Syncthing devices ==="
      replication_sources=$(update_replication_sources)
      rs_names=$(echo "${replication_sources}" | jq -c -r '.[].metadata.name')
      echo "=== Creating an Array for the names of replicationsources ==="
      echo "=== rs_names: ${rs_names}"
      IFS=$'\n' read -rd '' -a rs_names_array <<< "${rs_names}" || true

      echo "=== Loop through all ReplicationSources ==="
      for rs_name in "${rs_names_array[@]}"; do
        echo "=== Verifying ReplicationSource ${rs_name} ==="
        connected_status=$(all_peers_are_connected "${rs_name}")

        while [[ "${connected_status}" -ne 0 ]]; do
          echo "Wait for all Syncthing IDs in ${rs_name}'s peer list to be connected"
          sleep 5
          connected_status=$(all_peers_are_connected "${rs_name}")
        done
      done
