---
apiVersion: kuttl.dev/v1beta1
kind: TestAssert
timeout: 600
collectors:
  - type: command
    command: kubectl -n "$NAMESPACE" describe all,ep,pvc,volumesnapshot,replicationsource,replicationdestination
  - type: command
    command: kubectl -n "$NAMESPACE" logs -l "app.kubernetes.io/created-by=volsync" --all-containers=true --tail=-1

---
apiVersion: batch/v1
kind: Job
metadata:
  name: read-data
status:
  succeeded: 1
