---
apiVersion: kuttl.dev/v1beta1
kind: TestAssert
timeout: 600
collectors:
  - type: command
    command: kubectl -n "$NAMESPACE" describe all,pvc,volumesnapshot,replicationsource,replicationdestination

---
apiVersion: batch/v1
kind: Job
metadata:
  name: read-data
status:
  succeeded: 1
