---
# verify that the /data/testdata.txt file from test-data-1 exists on test-data-2 and test-data-3
apiVersion: batch/v1
kind: Job
metadata:
  name: read-data
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: reader
        image: busybox
        # validate that the testdata file contains "hello from syncthing-1"
        command: ["/bin/sh", "-c"]
        args: ["grep 'hello from syncthing-1' /data-2/testdata.txt"]
        volumeMounts:
        - name: test-data-2
          mountPath: /data-2
      restartPolicy: OnFailure
      volumes:
      - name: test-data-2
        persistentVolumeClaim:
          claimName: test-data-2
