---
# https://yamllint.readthedocs.io/en/stable/configuration.html

extends: default
ignore: |
  bundle/**
  config/**
  controllers/test/scc-crd.yml
  controllers/test/populator.storage.k8s.io_volumepopulators.yaml
  custom-scorecard-tests/**
  hack/crds/*
  helm/volsync/**
rules:
  indentation:
    indent-sequences: consistent
  line-length:
    allow-non-breakable-inline-mappings: true
    ignore: |
      kubectl-volsync/volsync.yaml
      test-kuttl/**
      test-e2e/**
