---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: source
spec:
  sourcePVC: data-source
  restic:
    pruneIntervalDays: 1
    repository: restic-repo
    retain:
      hourly: 3
      daily: 2
      monthly: 1
    copyMethod: None
    cacheCapacity: 1Gi
