---
- hosts: localhost
  tasks:
    - name: Create two namespaces
      include_role:
        name: create_namespace
      vars:
        num_namespaces: 2

    - name: Make sure it created exactly two
      fail:
        msg: "Wrong # of namespaces"
      when: (namespaces | length) != 2

    - name: Clear namespace list
      ansible.builtin.set_fact:
        namespaces: []

    - name: Create three more
      include_role:
        name: create_namespace
      vars:
        num_namespaces: 3

    - name: Make sure we got three
      fail:
        msg: "Wrong # of namespaces"
      when: namespaces | length != 3

    - name: Create single namespace
      include_role:
        name: create_namespace

    - name: Make sure we got one
      fail:
        msg: "Wrong # of namespaces"
      when: namespaces | length != 1
