---

- name: Check for required variables
  fail: msg="Variable {{ item }} must be defined to use this role"
  when: vars[var_check] is undefined
  with_items:
    - namespace
    - pvc_names
  loop_control:
    loop_var: var_check

- name: Create Deployment
  kubernetes.core.k8s:
    state: present
    template: deployment.yml.j2
  register: res

# Create Job that mounts the PVC and leave running
- name: Wait for Deployment to be ready
  kubernetes.core.k8s_info:
    api_version: apps/v1
    kind: Deployment
    name: "{{ res.result.metadata.name }}"
    namespace: "{{ namespace }}"
  register: res2
  until: >
    res2.resources | length > 0 and
    res2.resources[0].status.availableReplicas is defined and
    res2.resources[0].status.availableReplicas == 1
  delay: 1
  retries: "{{ timeout | default(300) }}"

- name: Save Deployment name
  ansible.builtin.set_fact:
    pvc_affinity_name: "{{ res.result.metadata.name }}"
