---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: destination
spec:
  trigger:
    manual: firstsync
  restic:
    repository: restic-repo
    #destinationPVC: data-dest
    cacheCapacity: 1Gi
    copyMethod: Snapshot
    accessModes: [ReadWriteOnce]
    capacity: 1Gi