---

- name: Get number of namespaces to create (default is 1)
  ansible.builtin.set_fact:
    nsrole_num_namespaces: "{{ num_namespaces | default(1) }}"

- name: Create namespace prefix
  ansible.builtin.set_fact:
    nsrole_namespace_prefix: "{{ 'test-%s-' | format(1000000 | random) }}"

- name: Create namespace list
  ansible.builtin.set_fact:
    namespaces: "{{ range(0, nsrole_num_namespaces|int) | map('regex_replace', '(\\d+)', nsrole_namespace_prefix + '\\1') }}"

- name: Add namespaces to master list
  ansible.builtin.set_fact:
    nsrole_all_created_namespaces: "{{ nsrole_all_created_namespaces|default([]) + namespaces }}"

- name: Create Namespaces
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ item }}"
  with_items: "{{ namespaces }}"
  notify: Delete temporary Namespaces

- name: Save name of first namespace (useful for tests that use 1 namespace)
  ansible.builtin.set_fact:
    namespace: "{{ namespaces[0] }}"
  when: nsrole_num_namespaces | int == 1

- name: Print out created namespaces
  ansible.builtin.debug:
    msg: namespaces {{ namespaces }} namespace is {{ namespace }}

- name: Set PSS enforcement mode
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ item }}"
        labels:
          pod-security.kubernetes.io/enforce: "{{ pss_enforce }}"
          security.openshift.io/scc.podSecurityLabelSync: "false"
  when: pss_enforce is defined
  with_items: "{{ namespaces }}"
